#:schema node_modules/wrangler/config-schema.json
name = "spellcaster"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./public" }

[observability.logs]
enabled = true